### PR TITLE
fix: failing CI check

### LINKED ISSUE #66: `CI / test (push) Failing after 3s`

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #66.

### CODE REVIEW

**Comment by hamirmahal** [comment]
@lpil can you make it so that contributors can see which checks are passing and failing in a pull request?

It doesn't show anything in my view.

image

**Comment by hamirmahal** [comment]
https://github.com/gleam-lang / [gleam](https://github.com/gleam-lang/gleam) does this.

image

That's from https://github.com/gleam-lang/gleam/pull/2879.

**Comment by lpil** [comment]
I don't know why it looks like that, I'm not aware of any such config

**Review by lpil — APPROVED** [review]
Thank you!

**Pull request merged**
